# Generated by Django 5.2.7 on 2025-10-22 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_empleado_departamento_empleado_direccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='empleado',
            name='puesto',
        ),
    ]
