# Generated by Django 5.2.7 on 2025-10-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_remove_empleado_departamento_remove_empleado_puesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='role',
            field=models.CharField(choices=[('empleado', 'Empleado'), ('manager', 'Manager'), ('admin', 'Administrador')], default='empleado', max_length=20),
        ),
    ]
