# Generated by Django 5.2.7 on 2025-10-23 10:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0005_empleado_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('tipo', models.CharField(choices=[('reunion', 'Reunión'), ('tarea', 'Tarea'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('asignados', models.ManyToManyField(blank=True, related_name='eventos_asignados', to='empleados.empleado')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_creados', to='empleados.empleado')),
            ],
        ),
    ]
